#!/usr/bin/env python3

#
# This script prints a JSON array containing all non-hidden subdirectories of
# the current working directory. As an example, if the current working
# directory contains the subdirectories "foo", "bar" and "baz", the output
# will be (the order of the directories is not necessarily alphabetical):
#
# ["foo", "bar", "baz"]
#
from genericpath import isdir
import json
import os

lines = list(open('./.github/scripts/diff.txt').readlines())
outlines = set()

#only add items that are directories
for line in lines:
    topFolder = line.split('/')[0]
    app = line.split('/')[1]
    if (topFolder == 'packages' and os.path.isdir(topFolder + '/' + app)):
        outlines.add(app)

print(json.dumps(list(outlines)))
